# permissions for end users to edit gsminilogs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gsminilog-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gsmini-log-operator
    app.kubernetes.io/part-of: gsmini-log-operator
    app.kubernetes.io/managed-by: kustomize
  name: gsminilog-editor-role
rules:
- apiGroups:
  - apps.gsmini.cn
  resources:
  - gsminilogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.gsmini.cn
  resources:
  - gsminilogs/status
  verbs:
  - get
