---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.gsmini.cn
  resources:
  - gsminilogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.gsmini.cn
  resources:
  - gsminilogs/finalizers
  verbs:
  - update
- apiGroups:
  - apps.gsmini.cn
  resources:
  - gsminilogs/status
  verbs:
  - get
  - patch
  - update
