apiVersion: apps.gsmini.cn/v1
kind: GsminiLog
metadata:
  labels:
    app.kubernetes.io/name: gsminilog
    app.kubernetes.io/instance: gsminilog-sample
    app.kubernetes.io/part-of: gsmini-log-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gsmini-log-operator
  name: gsminilog-sample
spec:
  # TODO(user): Add fields here
